### PR TITLE
Add admin unflag support + clean up admin detection

### LINKED ISSUE #56: Admins should have the capability to unflag a post
Design assumed all flagged posts would eventually be deleted. 

Thought: Have a `/unflag` route that's admin only.

### PR DESCRIPTION
**Pull request by kyl191**
Resolves #56

### CODE REVIEW

**Comment by TheKevJames** [comment]
Er... shouldn't `POST /social/<float:postid>/unflag` just be implemented as `DELETE /social/<float:postid>/flag`?

**Comment by kyl191** [comment]
That's for individual users reverting their flag.

This is for an admin to say "this post is fine, wipe out all the flags".

**Comment by TheKevJames** [comment]
So when an admin calls the `DELETE` route, set `flag_count` to 0?

**Comment by kyl191** [comment]
That assumes that an admin always wants to globally unflag a post.

It works, I suppose.

**Comment by TheKevJames** [comment]
I'd vote for that.. as is, the bulk of this code is just copied from the `DELETE .../flag` route. Plus, `un-` routes are a bit confusing given we already have rest verbs.

You could add an admin-only parameter for deleting all flag votes vs only their own.

**Review by TheKevJames — APPROVED** [review]

**Pull request merged**
